version: '3.8'

services:
  backend:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5072:5072"  # Adjust the port if needed
    shm_size: 2gb  # Increase shared memory size for Chromium
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/app  # Mount the current directory to /app in the container (optional)
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
