version: '3.8'

services:
  backend:
    build: .
    container_name: backendwebsite
    ports:
      - "5072:5072"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_PATH=/app/LocalDatabase/PersonalWebsite.db
    networks:
      - backend-network
    volumes:
      - .:/app
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge
