version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5072:5072"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/app
      - ./LocalDatabase:/app/LocalDatabase
